/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AutoMove from "./scripts/AutoMove"
import StartPanel from "./scripts/StartPanel"
import Player from "./scripts/Player"
import GamePanel from "./scripts/GamePanel"
import PausePanel from "./scripts/PausePanel"
import GameOverPanel from "./scripts/GameOverPanel"
import GameManager from "./scripts/GameManager"
import Car from "./scripts/Car"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1080;
    static height:number=1920;
    static scaleMode:string="showall";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Main.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("scripts/AutoMove.ts",AutoMove);
        reg("scripts/StartPanel.ts",StartPanel);
        reg("scripts/Player.ts",Player);
        reg("scripts/GamePanel.ts",GamePanel);
        reg("scripts/PausePanel.ts",PausePanel);
        reg("scripts/GameOverPanel.ts",GameOverPanel);
        reg("scripts/GameManager.ts",GameManager);
        reg("scripts/Car.ts",Car);
    }
}
GameConfig.init();