/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AutoMove from "./scripts/AutoMove"
import StartPanel from "./scripts/StartPanel"
import Player from "./scripts/Player"
import GameManager from "./scripts/GameManager"
import GamePanel from "./scripts/GamePanel"
import PausePanel from "./scripts/PausePanel"
import GameOverPanel from "./scripts/GameOverPanel"
import Car from "./scripts/Car"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/AutoMove.js",AutoMove);
		reg("scripts/StartPanel.js",StartPanel);
		reg("scripts/Player.js",Player);
		reg("scripts/GameManager.js",GameManager);
		reg("scripts/GamePanel.js",GamePanel);
		reg("scripts/PausePanel.js",PausePanel);
		reg("scripts/GameOverPanel.js",GameOverPanel);
		reg("scripts/Car.js",Car);
    }
}
GameConfig.width = 1080;
GameConfig.height = 1920;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Main.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
